apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.shortname" . }}-backend
  labels:
    app: {{ template "app.shortname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  {{- if (and (eq .Values.backend.service.type "LoadBalancer") (not (empty .Values.backend.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.backend.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.backend.service.externalPort }}
      targetPort: {{ .Values.backend.image.internalPort }}
      name: {{ .Values.backend.service.name }}
      {{- if .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "app.shortname" . }}-backend
    release: {{ .Release.Name }}